### ISSUE TITLE
Cascading World Gen

### ISSUE THREAD

**Issue by ghost** [Insane-96/CarbonadoMod#10]
I was having some problems with cascading world gen. Carbonado wasn't alone, in fact I think it was interacting with Recurrent Complex, but it was the most mentioned in the logs.

**Comment by Insane96** [comment]
Are you using the latest version?

**Comment by ghost** [comment]
Sorry, I meant to put that in. Yeah, I started a new world today and updated everything first.

...I didn't update Forge, if you think that would make a difference.

**Comment by Insane96** [comment]
Don't think so. But that's pretty strange since the newest Carbonado version uses a custom generator that is really basic, I really don't know why the hell it causes cascading world gen. I'll investigate but promise nothing.

**Comment by Insane96** [comment]
I really don't know why this happens
