### ISSUE TITLE
Can't craft carbanado gear in an anvil

### ISSUE THREAD

**Issue by Gelles** [Insane-96/CarbonadoMod#14]
Hello, hello!

Using the latest version of Carbonado Ore (1.5.0) and tried with both the current Recommended Forge (.2768)and the most updated (.2775). Tried in Creative, then again in Survival - Anvil takes the diamond gear on the left, the number of Carbonado, and shows the correct equivalent Carbonado gear, but I can't remove the Carbonado gear from the anvil. I've also tried unlocking all the correct tool advancements in case it was tied to that, to no effect.

No other mods installed except JEI.

Let me know if you need anything else, or if I'm just being a derp somehow.

Update: I did more testing. Damaged tools don't work, but enchanted ones (damaged or whole) DO work as expected.

My guess therefore is that the anvil is expecting an XP cost, and since the base diamond -> carbonado doesn't require XP it won't let me craft it.

**Comment by Insane96** [comment]
Can confirm, only happens for unenchanted items
