### ISSUE TITLE
[1.15.2] Carbonado recipies are not working

### ISSUE THREAD

**Issue by SlimF** [Insane-96/CarbonadoMod#23]
At first I thought it's some mod incompatibility, but I tried with only Carbonado installed and the bug persists. Tried in both survival and creative, nothing. JEI also doesn't list the recipies.

Versions:
Minecraft: 1.15.2
Forge: 31.1.47
Carbonado: Carbonado-2.0.3-mc1.15.2

![2020-04-25_18 30 54](https://user-images.githubusercontent.com/6482572/80283789-0bcfe300-8723-11ea-8cc1-2a0732c16dda.png)

**Comment by Insane96** [comment]
Fixed in 2.0.4
