### ISSUE TITLE
The creation of shards not working?

### ISSUE THREAD

**Issue by TheOrionsun** [Insane-96/CarbonadoMod#25]
MC 1.12.2, Carbonado 1.5.2-mc1.12.x

 Dropping anval from over stated height and get no shards.
I place the Carbonado block and place anvil against wall above, 30+ blocks, it drops down on top of Carbonado block and nothing happens except destroying the anvil.

Am I doing this correctly to get the shards?

**Comment by Insane96** [comment]
Carbonado item not block

**Comment by TheOrionsun** [comment]
Ah!!! I got it Thank you....
